#!/bin/bash

NAME=bibauthor
UTILFILE=util

DB2PATH=/home/db2inst2/sqllib
CC=gcc
CFLAGS=-I"$DB2PATH"/include 
LIBS="-L$DB2PATH/lib -ldb2"

rm -f "$NAME" "$NAME".c "$NAME".o "$NAME".bnd
rm -f "$UTILFILE" "$UTILFILE".o "$UTILFILE".bnd

db2 connect to cs348
db2 prep "$NAME".sqc bindfile
db2 bind "$NAME".bnd
db2 connect reset
"$CC" "$CFLAGS" -c "$NAME".c
"$CC" "$CFLAGS" -c "$UTILFILE".c
"$CC" "$CFLAGS" -o "$NAME" "$NAME".o "$UTILFILE".o $LIBS

NAME=bibcontent

rm -f "$NAME" "$NAME".c "$NAME".o "$NAME".bnd

db2 connect to cs348
db2 prep "$NAME".sqc bindfile
db2 bind "$NAME".bnd
db2 connect reset
"$CC" "$CFLAGS" -c "$NAME".c
"$CC" "$CFLAGS" -o "$NAME" "$NAME".o "$UTILFILE".o $LIBS
